import { createSlice } from "@reduxjs/toolkit";
import IPHONE1 from "../../../Assets/mobile-1.png";
import IPHONE2 from "../../../Assets/mobile-2.png";
import IPHONE3 from "../../../Assets/mobile-3.png";
import IPHONE4 from "../../../Assets/mobile-4.png";
import IPHONE5 from "../../../Assets/mobile-5.png";
import Camera1 from "../../../Assets/camera-1.png";
import Camera2 from "../../../Assets/camera-2.png";
import Camera3 from "../../../Assets/camera-3.png";
import Camera4 from "../../../Assets/camera-4.png";
import Camera5 from "../../../Assets/camera-5.png";
import watch1 from "../../../Assets/watch-1.png";
import watch2 from "../../../Assets/watch-2.png";
import watch3 from "../../../Assets/watch-3.png";
import watch4 from "../../../Assets/watch-4.png";
import watch5 from "../../../Assets/watch-5.png";
import watch6 from "../../../Assets/watch-6.png";
import watch7 from "../../../Assets/watch-7.png";
import Speaker1 from "../../../Assets/speaker-1.png";
import Speaker2 from "../../../Assets/speaker-2.png";
import Speaker3 from "../../../Assets/speaker-3.png";
import Speaker4 from "../../../Assets/speaker-4.png";
import Speaker5 from "../../../Assets/speaker-5.png";

const initialState = {
  cart: [
    {
      id: 1,
      title: "iPhone-11",
      image: IPHONE1,
      price: 10000,
      count: 0,
      totalamount: 10000,
      category: "mobile",
      specs: {
        screenSize: "6.1 inches",
        resolution: "2532 x 1170 pixels",
        processor: "A14 Bionic chip",
        storage: "64GB / 128GB / 256GB",
        camera: "Dual 12MP Ultra-Wide and Wide cameras",
        frontCamera: "12MP TrueDepth camera",
        videoRecording: "4K Dolby Vision HDR recording",
        faceID: "Yes",
        batteryLife: "Up to 17 hours of video playback",
        operatingSystem: "iOS 14",
        weightAndDimensions: "164 grams, 146.7 x 71.5 x 7.4 mm",
        additionalFeatures: "5G capable, Water and dust resistance (IP68)",
      },
    },
    {
      id: 2,
      title: "iPhone-2",
      image: IPHONE2,
      price: 10500,
      count: 0,
      totalamount: 10500,
      category: "mobile",
      specs: {
        screenSize: "6.1 inches",
        resolution: "2532 x 1170 pixels",
        processor: "A14 Bionic chip",
        storage: "64GB / 128GB / 256GB",
        camera: "Dual 12MP Ultra-Wide and Wide cameras",
        frontCamera: "12MP TrueDepth camera",
        videoRecording: "4K Dolby Vision HDR recording",
        faceID: "Yes",
        batteryLife: "Up to 17 hours of video playback",
        operatingSystem: "iOS 14",
        weightAndDimensions: "164 grams, 146.7 x 71.5 x 7.4 mm",
        additionalFeatures: "5G capable, Water and dust resistance (IP68)",
      },
    },
    {
      id: 3,
      title: "iPhone-3",
      image: IPHONE3,
      price: 10600,
      count: 0,
      totalamount: 10600,
      category: "mobile",
      specs: {
        screenSize: "6.1 inches",
        resolution: "2532 x 1170 pixels",
        processor: "A14 Bionic chip",
        storage: "64GB / 128GB / 256GB",
        camera: "Dual 12MP Ultra-Wide and Wide cameras",
        frontCamera: "12MP TrueDepth camera",
        videoRecording: "4K Dolby Vision HDR recording",
        faceID: "Yes",
        batteryLife: "Up to 17 hours of video playback",
        operatingSystem: "iOS 14",
        weightAndDimensions: "164 grams, 146.7 x 71.5 x 7.4 mm",
        additionalFeatures: "5G capable, Water and dust resistance (IP68)",
      },
    },
    {
      id: 4,
      title: "iPhone-4",
      image: IPHONE4,
      price: 10700,
      count: 0,
      totalamount: 10700,
      category: "mobile",
      specs: {
        screenSize: "6.1 inches",
        resolution: "2532 x 1170 pixels",
        processor: "A14 Bionic chip",
        storage: "64GB / 128GB / 256GB",
        camera: "Dual 12MP Ultra-Wide and Wide cameras",
        frontCamera: "12MP TrueDepth camera",
        videoRecording: "4K Dolby Vision HDR recording",
        faceID: "Yes",
        batteryLife: "Up to 17 hours of video playback",
        operatingSystem: "iOS 14",
        weightAndDimensions: "164 grams, 146.7 x 71.5 x 7.4 mm",
        additionalFeatures: "5G capable, Water and dust resistance (IP68)",
      },
    },
    {
      id: 5,
      title: "iPhone-5",
      image: IPHONE5,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "mobile",
      specs: {
        screenSize: "6.1 inches",
        resolution: "2532 x 1170 pixels",
        processor: "A14 Bionic chip",
        storage: "64GB / 128GB / 256GB",
        camera: "Dual 12MP Ultra-Wide and Wide cameras",
        frontCamera: "12MP TrueDepth camera",
        videoRecording: "4K Dolby Vision HDR recording",
        faceID: "Yes",
        batteryLife: "Up to 17 hours of video playback",
        operatingSystem: "iOS 14",
        weightAndDimensions: "164 grams, 146.7 x 71.5 x 7.4 mm",
        additionalFeatures: "5G capable, Water and dust resistance (IP68)",
      },
    },
    {
      id: 6,
      title: "Watch-1",
      image: watch1,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 7,
      title: "Watch-2",
      image: watch2,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 8,
      title: "Watch-3",
      image: watch3,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 9,
      title: "Watch-4",
      image: watch4,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 10,
      title: "Watch-5",
      image: watch5,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 11,
      title: "Watch-6",
      image: watch6,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 12,
      title: "Watch-7",
      image: watch7,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "watch",
      specs: {
        displayType: "AMOLED",
        displaySize: "1.3 inches",
        resolution: "360 x 360 pixels",
        processor: "Dual-core",
        storage: "4GB",
        batteryLife: "Up to 5 days",
        waterResistance: "Waterproof (50 meters)",
        sensors: "Heart rate sensor, GPS, Accelerometer, Gyroscope",
        connectivity: "Bluetooth 5.0, Wi-Fi",
        compatibility: "iOS and Android",
        strapMaterial: "Silicone",
        weightAndDimensions: "50 grams, 42 x 42 x 11 mm",
        additionalFeatures: "Fitness tracking, Sleep tracking, Notifications",
      },
    },
    {
      id: 13,
      title: "speaker-1",
      image: Speaker1,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "speaker",
      specs: {
        speakerType: "Portable Bluetooth Speaker",
        outputPower: "20W",
        batteryLife: "Up to 10 hours",
        connectivity: "Bluetooth 5.0, AUX-in",
        waterResistance: "Splash-resistant",
        dimensions: "180 x 80 x 80 mm",
        weight: "500 grams",
        additionalFeatures:
          "Built-in microphone for hands-free calls, LED indicators",
      },
    },
    {
      id: 14,
      title: "speaker-2",
      image: Speaker2,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "speaker",
      specs: {
        speakerType: "Portable Bluetooth Speaker",
        outputPower: "20W",
        batteryLife: "Up to 10 hours",
        connectivity: "Bluetooth 5.0, AUX-in",
        waterResistance: "Splash-resistant",
        dimensions: "180 x 80 x 80 mm",
        weight: "500 grams",
        additionalFeatures:
          "Built-in microphone for hands-free calls, LED indicators",
      },
    },
    {
      id: 14,
      title: "speaker-3",
      image: Speaker3,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "speaker",
      specs: {
        speakerType: "Portable Bluetooth Speaker",
        outputPower: "20W",
        batteryLife: "Up to 10 hours",
        connectivity: "Bluetooth 5.0, AUX-in",
        waterResistance: "Splash-resistant",
        dimensions: "180 x 80 x 80 mm",
        weight: "500 grams",
        additionalFeatures:
          "Built-in microphone for hands-free calls, LED indicators",
      },
    },
    {
      id: 15,
      title: "speaker-4",
      image: Speaker4,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "speaker",
      specs: {
        speakerType: "Portable Bluetooth Speaker",
        outputPower: "20W",
        batteryLife: "Up to 10 hours",
        connectivity: "Bluetooth 5.0, AUX-in",
        waterResistance: "Splash-resistant",
        dimensions: "180 x 80 x 80 mm",
        weight: "500 grams",
        additionalFeatures:
          "Built-in microphone for hands-free calls, LED indicators",
      },
    },
    {
      id: 16,
      title: "speaker-5",
      image: Speaker5,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "speaker",
      specs: {
        speakerType: "Portable Bluetooth Speaker",
        outputPower: "20W",
        batteryLife: "Up to 10 hours",
        connectivity: "Bluetooth 5.0, AUX-in",
        waterResistance: "Splash-resistant",
        dimensions: "180 x 80 x 80 mm",
        weight: "500 grams",
        additionalFeatures:
          "Built-in microphone for hands-free calls, LED indicators",
      },
    },
    {
      id: 17,
      title: "camera-1",
      image: Camera1,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "camera",
      specs: {
        resolution: "24 megapixels",
        sensorTypeAndSize: "CMOS, Full Frame",
        lensTypeAndAperture: "Zoom, f/2.8",
        isoSensitivity: "100-25600",
        shutterSpeed: "1/8000 to 30 seconds",
        autofocusSystem: "Phase-detection",
        imageStabilization: "In-body",
        viewfinderAndDisplay: "Optical viewfinder, 3-inch LCD",
        videoCapabilities: "4K at 30fps",
        burstShooting: "6 frames per second",
        wirelessConnectivity: "Wi-Fi, Bluetooth",
        storage: "SD card slot",
        batteryLife: "Approximately 800 shots per charge",
        weightAndDimensions: "Approx. 800g, 150 x 120 x 80mm",
        additionalFeatures: "Weather-sealed, Customizable settings",
      },
    },
    {
      id: 18,
      title: "camera-2",
      image: Camera2,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "camera",
      specs: {
        resolution: "24 megapixels",
        sensorTypeAndSize: "CMOS, Full Frame",
        lensTypeAndAperture: "Zoom, f/2.8",
        isoSensitivity: "100-25600",
        shutterSpeed: "1/8000 to 30 seconds",
        autofocusSystem: "Phase-detection",
        imageStabilization: "In-body",
        viewfinderAndDisplay: "Optical viewfinder, 3-inch LCD",
        videoCapabilities: "4K at 30fps",
        burstShooting: "6 frames per second",
        wirelessConnectivity: "Wi-Fi, Bluetooth",
        storage: "SD card slot",
        batteryLife: "Approximately 800 shots per charge",
        weightAndDimensions: "Approx. 800g, 150 x 120 x 80mm",
        additionalFeatures: "Weather-sealed, Customizable settings",
      },
    },
    {
      id: 19,
      title: "camera-3",
      image: Camera3,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "camera",
      specs: {
        resolution: "24 megapixels",
        sensorTypeAndSize: "CMOS, Full Frame",
        lensTypeAndAperture: "Zoom, f/2.8",
        isoSensitivity: "100-25600",
        shutterSpeed: "1/8000 to 30 seconds",
        autofocusSystem: "Phase-detection",
        imageStabilization: "In-body",
        viewfinderAndDisplay: "Optical viewfinder, 3-inch LCD",
        videoCapabilities: "4K at 30fps",
        burstShooting: "6 frames per second",
        wirelessConnectivity: "Wi-Fi, Bluetooth",
        storage: "SD card slot",
        batteryLife: "Approximately 800 shots per charge",
        weightAndDimensions: "Approx. 800g, 150 x 120 x 80mm",
        additionalFeatures: "Weather-sealed, Customizable settings",
      },
    },
    {
      id: 20,
      title: "camera-4",
      image: Camera4,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "camera",
      specs: {
        resolution: "24 megapixels",
        sensorTypeAndSize: "CMOS, Full Frame",
        lensTypeAndAperture: "Zoom, f/2.8",
        isoSensitivity: "100-25600",
        shutterSpeed: "1/8000 to 30 seconds",
        autofocusSystem: "Phase-detection",
        imageStabilization: "In-body",
        viewfinderAndDisplay: "Optical viewfinder, 3-inch LCD",
        videoCapabilities: "4K at 30fps",
        burstShooting: "6 frames per second",
        wirelessConnectivity: "Wi-Fi, Bluetooth",
        storage: "SD card slot",
        batteryLife: "Approximately 800 shots per charge",
        weightAndDimensions: "Approx. 800g, 150 x 120 x 80mm",
        additionalFeatures: "Weather-sealed, Customizable settings",
      },
    },
    {
      id: 21,
      title: "camera-5",
      image: Camera5,
      price: 10800,
      count: 0,
      totalamount: 10800,
      category: "camera",
      specs: {
        resolution: "24 megapixels",
        sensorTypeAndSize: "CMOS, Full Frame",
        lensTypeAndAperture: "Zoom, f/2.8",
        isoSensitivity: "100-25600",
        shutterSpeed: "1/8000 to 30 seconds",
        autofocusSystem: "Phase-detection",
        imageStabilization: "In-body",
        viewfinderAndDisplay: "Optical viewfinder, 3-inch LCD",
        videoCapabilities: "4K at 30fps",
        burstShooting: "6 frames per second",
        wirelessConnectivity: "Wi-Fi, Bluetooth",
        storage: "SD card slot",
        batteryLife: "Approximately 800 shots per charge",
        weightAndDimensions: "Approx. 800g, 150 x 120 x 80mm",
        additionalFeatures: "Weather-sealed, Customizable settings",
      },
    },
  ],
  filteredItems: [],
};
export const cartSlice = createSlice({
  name: "cartSlice",
  initialState,
  reducers: {
    cart(state, action) {
    },
    filter: (state, action) => {
        state.filteredItems = action.payload;
      },
      cart(state, action) {
        const { count, key, opr } = action.payload;
  
        console.log(count, key, opr);
        if (opr === "add") {
          state.cart[key].totalamount = count * state.cart[key].price;
          state.cart[key].count = count;
          
          
        } else{
          state.cart[key].totalamount = count * state.cart[key].price;
          state.cart[key].count = count;
        }
        if ( state.cart[key].count === 0) {
          state.cart.splice(key, 1);
      }
        
      },
      removeCart(state,action){
          const {key,opr}= action.payload
         
          
          state.cart.splice(key, 1);
      }
  },
});

export const {filter,cart,removeCart} = cartSlice.actions
export default cartSlice.reducer;
